### ISSUE TITLE
building the optee_os fails

### ISSUE THREAD

**Issue by namkedia** [op-tee-ia/optee_os#7]
I am building optee_os in this repo for QEMU platform, no cross compilation and gcc. It fails with the following: 
ld.bfd -T core/arch/x86_64/kernel/link_dummy.ld --no-check-sections --gc-sections \
	`cat /home/nk/optee/out/optee_os/core/init_entries.txt` \
	 /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/user_ta.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/ree_fs_ta.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/secstor_ta.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/pseudo_ta.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/elf_load.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/tee_time.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/otp_stubs.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/descriptor.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/fault.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/gdt.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/exceptions.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/fpu.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/tee_time_ree.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/spin_lock_64.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/spin_lock_debug.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/thread_64.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/thread.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/trace_ext.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/misc_64.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/mutex.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/wait_queue.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/pm_stubs.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/generic_boot.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/generic_entry_64.o /home/nk/optee/out/optee_os/core/arch/x86_64/kernel/link_dummies.o /home/nk/optee/out/optee_os/core/arch/x86_64/mm/core_mmu.o /home/nk/optee/out/optee_os/core/arch/x86_64/mm/tee_mmu.o /home/nk/optee/out/optee_os/core/arch/x86_64/mm/tee_mm.o /home/nk/optee/out/optee_os/core/arch/x86_64/mm/pgt_cache.o /home/nk/optee/out/optee_os/core/arch/x86_64/mm/mobj.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/arch_svc_64.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/arch_svc.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/pta_socket.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/entry_std.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/entry_fast.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/init.o /home/nk/optee/out/optee_os/core/arch/x86_64/tee/cache.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/pta_invoke_tests.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/core_self_tests.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/interrupt_tests.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/core_mutex_tests.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/core_fs_htree_tests.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/secstor_ta_mgmt.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/stats.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/system.o /home/nk/optee/out/optee_os/core/arch/x86_64/pta/device.o /home/nk/optee/out/optee_os/core/arch/x86_64/plat-bxtp/main.o /home/nk/optee/out/optee_os/core/arch/x86_64/sm/vmcall.o /home/nk/optee/out/optee_os/core/kernel/assert.o /home/nk/optee/out/optee_os/core/kernel/console.o /home/nk/optee/out/optee_os/core/kernel/pm.o /home/nk/optee/out/optee_os/core/kernel/handle.o /home/nk/optee/out/optee_os/core/kernel/interrupt.o /home/nk/optee/out/optee_os/core/kernel/msg_param.o /home/nk/optee/out/optee_os/core/kernel/panic.o /home/nk/optee/out/optee_os/core/kernel/refcount.o /home/nk/optee/out/optee_os/core/kernel/tee_misc.o /home/nk/optee/out/optee_os/core/kernel/tee_ta_manager.o /home/nk/optee/out/optee_os/core/kernel/scattered_array.o /home/nk/optee/out/optee_os/core/crypto/crypto.o /home/nk/optee/out/optee_os/core/crypto/aes-gcm.o /home/nk/optee/out/optee_os/core/crypto/aes-gcm-sw.o /home/nk/optee/out/optee_os/core/crypto/aes-gcm-ghash-tbl.o /home/nk/optee/out/optee_os/core/crypto/signed_hdr.o /home/nk/optee/out/optee_os/core/crypto/rng_fortuna.o /home/nk/optee/out/optee_os/core/tee/tee_cryp_utl.o /home/nk/optee/out/optee_os/core/tee/tee_cryp_hkdf.o /home/nk/optee/out/optee_os/core/tee/tee_cryp_concat_kdf.o /home/nk/optee/out/optee_os/core/tee/tee_cryp_pbkdf2.o /home/nk/optee/out/optee_os/core/tee/tee_svc.o /home/nk/optee/out/optee_os/core/tee/tee_svc_cryp.o /home/nk/optee/out/optee_os/core/tee/tee_svc_storage.o /home/nk/optee/out/optee_os/core/tee/tee_ree_fs.o /home/nk/optee/out/optee_os/core/tee/fs_htree.o /home/nk/optee/out/optee_os/core/tee/fs_dirfile.o /home/nk/optee/out/optee_os/core/tee/tee_fs_rpc.o /home/nk/optee/out/optee_os/core/tee/tee_fs_rpc_cache.o /home/nk/optee/out/optee_os/core/tee/tee_fs_key_manager.o /home/nk/optee/out/optee_os/core/tee/tee_obj.o /home/nk/optee/out/optee_os/core/tee/tee_pobj.o /home/nk/optee/out/optee_os/core/tee/tee_time_generic.o /home/nk/optee/out/optee_os/core/tee/tadb.o /home/nk/optee/out/optee_os/core/tee/uuid.o /home/nk/optee/out/optee_os/core/drivers/uart.o /home/nk/optee/out/optee_os/core/drivers/apic.o /home/nk/optee/out/optee_os/core/ta_pub_key.o /home/nk/optee/out/optee_os/core/version.o   -L/home/nk/optee/out/optee_os/core/lib/libtomcrypt -L/home/nk/optee/out/optee_os/core-lib/libmbedtls -L/home/nk/optee/out/optee_os/core-lib/libutils -ltomcrypt -lmbedtls -lutils /usr/lib/gcc/x86_64-linux-gnu/4.9/libgcc.a -o /home/nk/optee/out/optee_os/core/init.o
**ld.bfd: /home/nk/optee/out/optee_os/core/init.o: could not find output section .rela.dyn for input section .rela.dyn**
ld.bfd: final link failed: Nonrepresentable section on output
core/arch/x86_64/kernel/link.mk:77: recipe for target '/home/nk/optee/out/optee_os/core/init.o' failed
make[1]: *** [/home/nk/optee/out/optee_os/core/init.o] Error 1
make[1]: Leaving directory '/home/nk/optee/optee_os'
Makefile:53: recipe for target 'optee_os' failed

Any thoughts on why this is happening and how to fix it?

**Comment by jingdlu** [comment]
Hi,

1, First of all, op-tee x86 doesn't support QEMU x86 platform fully, because op-tee x86 solution depends on hypervisor(ikgt), we use this lite hypervisor to isolate REE and TEE. However, currently we can't run ikgt on QEMU. For op-tee x86 fully supporting platforms and compilation, please refer to the following link:
https://github.com/op-tee-ia/manifest/wiki

2, If you still need to compile and run op-tee-ia on qemu standalone, please follow above link to pull code , then change "OPTEE_OS_ENV_VAR += PLATFORM=bxtp" to "OPTEE_OS_ENV_VAR += PLATFORM=qemu" in Makefile, then make compilation, you will find op-tee binary (tee-pager.bin) in out/optee_os/core/ folder, and run it on QEMU.
